-- Optional seed data for testing (run after migration)
INSERT INTO public.employees (
  full_name,
  father_name,
  mother_name,
  date_of_birth,
  age,
  mobile_number,
  employee_type,
  salary_basis,
  machine_assignment,
  family_members,
  document_paths,
  esi_enabled,
  pf_enabled,
  fooding_allowance,
  bonus_last_year
) VALUES
(
  'Rahul Sharma',
  'Rajesh Sharma',
  'Sunita Sharma',
  '1992-03-15',
  33,
  '9876543210',
  'Regular',
  'Monthly',
  'Machine A',
  '[{"id":"f1","fullName":"Sunita Sharma","relationship":"Mother","esiRole":"Dependent Parent"}]'::jsonb,
  '{}'::jsonb,
  true,
  true,
  'Daily Allowance',
  15000.00
),
(
  'Priya Verma',
  'Anil Verma',
  'Kavita Verma',
  '1995-08-22',
  30,
  '9123456780',
  'Contractor',
  'Contract-based',
  'Machine B',
  '[]'::jsonb,
  '{}'::jsonb,
  false,
  true,
  'Provided by Company',
  8000.00
),
(
  'Amit Kumar',
  'Suresh Kumar',
  'Rekha Kumar',
  '1998-11-05',
  27,
  '9988776655',
  'Temporary',
  'Daily',
  'None',
  '[{"id":"f2","fullName":"Rekha Kumar","relationship":"Mother","esiRole":"Dependent Parent"}]'::jsonb,
  '{}'::jsonb,
  true,
  false,
  'Self-managed',
  5000.00
);
