import type { EmployeeListItem } from "@/types/employee-list";
import { splitFullName } from "@/lib/employee-name-utils";

/** Legacy mock data — app now uses Supabase. Kept for reference/tests only. */
export const MOCK_EMPLOYEES: EmployeeListItem[] = [
  {
    id: "emp-001",
    name: "Rahul Sharma",
    ...splitFullName("Rahul Sharma"),
    employeeType: "Regular",
    mobileNumber: "9876543210",
    machineAssignment: "Machine A",
    fixSalaryAmount: 25000,
    variableSalaryEnabled: false,
    dailyRate: null,
    workedDays: null,
    effectiveSalary: 25000,
    assignedFromGroup: "Krishna Food Product",
    esiStatus: "Active",
    pfStatus: "Active",
    salaryBasis: "Daily",
    hasAttendanceRecords: false,
    overtimeHourlyRate: 400,
  },
  {
    id: "emp-002",
    name: "Priya Verma",
    ...splitFullName("Priya Verma"),
    employeeType: "Contractor",
    mobileNumber: "9123456780",
    machineAssignment: "Machine B",
    fixSalaryAmount: null,
    variableSalaryEnabled: true,
    dailyRate: 800,
    workedDays: 22,
    effectiveSalary: 17600,
    assignedFromGroup: "Contractor 2",
    esiStatus: "Non-Active",
    pfStatus: "Non-Active",
    salaryBasis: "Daily",
    hasAttendanceRecords: true,
    overtimeHourlyRate: 300,
  },
  {
    id: "emp-003",
    name: "Amit Kumar",
    ...splitFullName("Amit Kumar"),
    employeeType: "Temporary",
    mobileNumber: "9988776655",
    machineAssignment: "—",
    fixSalaryAmount: 18000,
    variableSalaryEnabled: false,
    dailyRate: null,
    workedDays: null,
    effectiveSalary: 18000,
    assignedFromGroup: "MAHEK Industries",
    esiStatus: "Active",
    pfStatus: "Active",
    salaryBasis: "",
    hasAttendanceRecords: false,
    overtimeHourlyRate: 500,
  },
];
